apiVersion: v1
kind: Secret
metadata:
  name: opensearch
  namespace: {{ .Release.Namespace | quote }}
stringData:
  opensearch-password: {{ .Values.opensearch.password }}
  opensearch-dashboards-password: {{ .Values.opensearchDashboards.password }}
  logstash-password: {{ .Values.opensearch.logstash.password }}
