{{- $envVars := include "find.common.env" (list . .Values.backend) -}}
{{- $fullName := include "find.backend.fullname" . -}}
{{- $component := "backend" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "find.common.labels" (list . $component) | nindent 4 }}
  annotations:
    {{- toYaml $.Values.backend.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "find.common.selectorLabels" (list . $component) | nindent 4 }}
