# Generated by Django 5.1.4 on 2025-09-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='client_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='services',
            field=models.ManyToManyField(blank=True, to='core.service', verbose_name='Allowed services for search'),
        ),
    ]
