# Generated by Django 6.0.5 on 2026-06-01 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_client_id_service_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='services',
        ),
    ]
