# Generated by Django 6.0.4 on 2026-05-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_client_id_service_services'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='service',
            name='token_length_exact_50',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
